<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyTiecCuoi" Class="QLTCDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-2E24HCM;Initial Catalog=QuanLyTiecCuoi;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="QuanLyTiecCuoiConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DATTIEC" Member="DATTIECs">
    <Type Name="DATTIEC">
      <Column Name="MaDT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NgayDT" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Ca" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TienDC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SLBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaSanh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoBanDuTru" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MaHD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayThanhToan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenCR" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TenCD" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Menu" Member="Menus">
    <Type Name="Menu">
      <Column Name="MaMenu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaHD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuiDinh" Member="QuiDinhs">
    <Type Name="QuiDinh">
      <Column Name="MaQD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenQD" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Phat" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SANH" Member="SANHs">
    <Type Name="SANH">
      <Column Name="MaSanh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSanh" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LoaiSanh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuongMax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGiaMin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>